AM Data Location
mulesoft/docs-monitoring pull request #155
Opened 2021-02-04 00:45 UTC by juanpablotimpanaro

2021-02-04 01:18 UTC, jiang-wu requested changes

2021-02-04 01:18 UTC, jiang-wu commented on modules/ROOT/pages/index.adoc
> +** Metric data in the same region as your control plane: US East (N. Virginia) or EU (Frankfurt)
Stores metric data ...

2021-02-04 01:18 UTC, jiang-wu commented on modules/ROOT/pages/index.adoc
> +** Log and metric data in the same region as your control plane: US East (N. Virginia) or EU (Frankfurt)
Stores log and metric ...

2021-02-04 01:18 UTC, jiang-wu commented on modules/ROOT/pages/index.adoc
> +* For Gold/Platinium
For Gold and Platinum subscriptions

2021-02-04 01:18 UTC, jiang-wu commented on modules/ROOT/pages/index.adoc
> +* For Titanium
For Titanium subscription

2021-02-04 02:08 UTC, jiang-wu approved these changes

2021-02-04 02:10 UTC, jiang-wu commented
For https://www.mulesoft.org/jira/browse/DOCS-10085

2021-02-04 02:21 UTC, michael-lee-mulesoft approved these changes

2021-02-11 18:54 UTC, sarathecoubian approved these changes

2021-02-11 18:54 UTC, merged